### PR TITLE
Career feature implementation 

### LINKED ISSUE #26: Career Feature

### PR DESCRIPTION
**Pull request by sunnyt02**
This pull request includes the implementation of the new career feature without the ML component. Specifically, users now should be able to:
1. register as recruiter user type
2. view new career page (both student and recruiter view)
3. students can submit their information
4. recruiters can view students' information

This pull request made changes/additions to the following files:
1. public/src/client/career.js: added form for students to provide information
2. src/controllers/authentication.js: added authentication for recruiter user type
3. src/controllers/career.js: added for recruiters to view students info
4. src/controllers/index.js: added recruiter user type in registration page
5. src/controllers/write/career.js: process students information and use ML model to apply prediction
6. src/user/career.js: get user data
7. src/user/index.js: imported career files
8. themes/nodebb-theme-persona/less/career.less: frontend style
9. themes/nodebb-theme-persona/templates/career.tpl: imported student and recruiter.tpl
10. themes/nodebb-theme-persona/templates/partials/career/recruiter.tpl: recruiter career page
11. themes/nodebb-theme-persona/templates/partials/career/student.tpl: student career page

Next step: need to implement and integrate ML microservice via API in order to obtain full functionality of the feature

### CODE REVIEW

**Review by Ireoluwa-A — APPROVED** [review]
Great! Ensured that new link is up and running

**Review by victorwa22 — COMMENTED** [review]
Looks good, microservice works as expected

**Review by JuliaZhang7 — APPROVED** [review]
work on my side

**Review by zhihengy — APPROVED** [review]
Looks good

**Pull request merged**
